return {
   [ "fatih/vim-go" ] = {},
   [ "https://tpope.io/vim/fugitive.git" ] = {},
   [ "thaerkh/vim-workspace" ] = {},
   [ "airblade/vim-gitgutter" ] = {},
   [ "scrooloose/nerdtree" ] = {},
   [ "vim-ctrlspace/vim-ctrlspace" ] = {},
   [ "ryanoasis/vim-devicons" ] = {},
   [ "hashivim/vim-terraform" ] = {},
   [ "mileszs/ack.vim" ] = {},
   [ "troydm/easybuffer.vim" ] = {},
   [ "editorconfig/editorconfig-vim" ] = {},
   [ "preservim/nerdcommenter" ] = {},
   [ "junegunn/fzf.vim" ] = {},
   [ "pearofducks/ansible-vim" ] = {},
   [ "preservim/tagbar" ] = {},
   [ "KeitaNakamura/neodark.vim" ] = {},
   [ "doums/darcula" ] = {},
}

